image:
  name: antora/antora:1.0.0
  entrypoint: [/bin/sh, -c]
cache:
  paths:
  - .cache/
generate:
  stage: build
  # variables is not yet supported by gitlab.com
  #except:
  #  variables:
  #  - $NETLIFY_SITE_ID
  except:
  - schedules
  script:
  - antora --url=https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/browse/public --pull site.yml
  artifacts:
    expire_in: 1 week
    paths:
    - public/
# deploy/netlify is used by nightly job
deploy/netlify:
  stage: deploy
  # variables is not yet supported by gitlab.com
  #only:
  #  variables:
  #  - $NETLIFY_SITE_ID
  only:
  - schedules
  before_script:
  - yarn add netlify-cli --prefer-offline --cache-folder .cache/yarn --no-lockfile > /dev/null
  - rm -f package.json
  script:
  - antora --google-analytics-key=UA-112324747-2 --html-url-extension-style=indexify --pull site.yml
  - ./node_modules/.bin/netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./public
