image:
  name: antora/antora:1.0.0
  entrypoint: [/bin/sh, -c]
cache:
  paths:
  - .cache/
netlify:
  stage: deploy
  before_script:
  - yarn global add netlify-cli > /dev/null
  script:
  - antora --google-analytics-key=UA-112324747-2 --html-url-extension-style=indexify --pull site.yml
  - netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./public
  only:
  - master@antora/docs.antora.org
