image:
  name: antora/antora:1.0.0-rc.2
  entrypoint: [/bin/sh, -c]
cache:
  paths:
  - .cache
pages:
  stage: deploy
  script:
  - antora --google-analytics-key=UA-112324747-2 --html-url-extension-style=indexify --pull site.yml
  artifacts:
    paths:
    - public
  only:
  - master
