image:
  name: antora/antora:1.0.0-beta.1
  entrypoint: ["/bin/sh", "-c"]
cache:
  paths:
  - .cache
pages:
  stage: deploy
  script:
  - antora --google-analytics-key=UA-112324747-2 --html-url-extension-style=indexify site.yml
  - "echo 'User-agent: *' > public/robots.txt"
  - rm -rf .cache/antora/ui
  artifacts:
    paths:
    - public
  only:
  - master
