image: node:8
before_script:
- yarn --cache-folder=.yarn-cache add @antora/cli @antora/site-generator-default > /dev/null
cache:
  paths:
  - .yarn-cache
pages:
  stage: deploy
  script:
  #- $(npm bin)/antora --google-analytics-key=UA-112324747-2 --html-url-extension-style=indexify site.yml
  #- echo 'User-agent: *' > public/robots.txt
  # BEGIN temporary
  - mkdir -p public
  - echo '<!DOCTYPE html><html><body><h1>docs.antora.org</h1><p>Coming soon!</p></body></html>' > public/index.html
  # END temporary
  artifacts:
    paths:
    - public
  only:
  - master
