image: node:8
before_script:
- yarn --cache-folder=.yarn-cache add @antora/cli @antora/site-generator-default > /dev/null
cache:
  paths:
  - .yarn-cache
pages:
  stage: deploy
  script:
  #- $(npm bin)/antora site.yml
  - mkdir -p public
  - echo '<!DOCTYPE html><html><body><h1>docs.antora.org</h1><p>Coming soon!</p></body></html>' > public/index.html
  - echo '<!DOCTYPE html><html><body><h1>docs.antora.org</h1><p>Test Page</p></body></html>' > public/test.html
  artifacts:
    paths:
    - public
  only:
  - master
