runtime:
  cache_dir: ./.cache/antora
site:
  title: Antora Docs (Preview)
  url: https://preview.docs.antora.org
  start_page: antora::index.adoc
  robots: disallow
content:
  sources:
  - url: https://gitlab.com/antora/antora.git
    start_path: docs
    branches: master, v2.2.x, v2.1.x, v2.0.x
  - url: https://gitlab.com/antora/antora-ui-default.git
    start_path: docs
    branches: master
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
