[build]
  base = "netlify"
  publish = "public"
  command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull ../antora-playbook.yml"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production.environment]
  ALGOLIA_API_KEY = "47f6ef672cdc3d3e64709f68fae72956"
  ALGOLIA_INDEX_NAME = "antora"
  GOOGLE_ANALYTICS_KEY = "UA-112324747-2"

[context.deploy-preview]
  command = "node_modules/.bin/antora --url $DEPLOY_PRIME_URL --html-url-extension-style=indexify --pull ../antora-playbook.yml"

# netlify.toml does not get used for nightly deploys; use settings from _headers file instead
#[[headers]]
#  for = "/_/font/*"
#  [headers.values]
#    Cache-Control = "public,max-age=604800"
