[build]
base = "netlify"
publish = "public"

[build.environment]
NODE_VERSION = "12"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.branch-deploy]
command = """\
node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml && \
node_modules/.bin/antora --url $DEPLOY_PRIME_URL --html-url-extension-style=indexify --redirect-facility=netlify ../antora-playbook.yml\
"""

#[context.branch-deploy.environment]
#ALGOLIA_APP_ID = "E80Q5UHPOS"
#ALGOLIA_API_KEY = "6e7248a6d21038512a92145e9b903757"
#ALGOLIA_IDX_NAME = "antora-docs-preview"

[context.deploy-preview]
command = """\
node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml && \
node_modules/.bin/antora --url $DEPLOY_PRIME_URL --html-url-extension-style=indexify --redirect-facility=netlify ../antora-playbook.yml\
"""

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"

# NOTE the following redirects get appended to the redirects defined in the _redirects file

[[redirects]]
from = "/antora/1.0/*"
to = "/antora/latest/:splat"
status = 301

[[redirects]]
from = "/antora/1.1/*"
to = "/antora/latest/:splat"
status = 301

[[redirects]]
from = "/antora/latest/*"
to = "/antora/2.2/:splat"
status = 302
