[build]
  base = "netlify"
  publish = "public"
  command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull ../site.yml"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production.environment]
  GOOGLE_ANALYTICS_KEY = "UA-112324747-2"

[context.deploy-preview]
  command = "URL=$DEPLOY_URL node_modules/.bin/antora --html-url-extension-style=indexify --pull ../site.yml"

# we could switch to /_/* and use an indefinite age if we append a cache busters to the asset URLs
[[headers]]
  for = "/_/font/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
