[build]
base = "netlify"
publish = "public"
command = "NODE_PATH=node_modules node_modules/.bin/antora --pull --generator=../generator/xref-validator.js ../antora-playbook.yml && node_modules/.bin/antora --html-url-extension-style=indexify --redirect-facility=netlify ../antora-playbook.yml"

[build.environment]
NODE_VERSION = "8"
BUILD_ONLY = "true"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production.environment]
ALGOLIA_API_KEY = "47f6ef672cdc3d3e64709f68fae72956"
ALGOLIA_INDEX_NAME = "antora"
GOOGLE_ANALYTICS_KEY = "UA-112324747-2"

[context.deploy-preview]
command = "NODE_PATH=node_modules node_modules/.bin/antora --pull --generator=../generator/xref-validator.js ../antora-playbook.yml && node_modules/.bin/antora --url $DEPLOY_PRIME_URL --html-url-extension-style=indexify --redirect-facility=netlify ../antora-playbook.yml"

# use settings from _headers file to allow use of netlify command (not currently used)
#[[headers]]
#for = "/_/font/*"
#  [headers.values]
#  Cache-Control = "public,max-age=604800"

[[redirects]]
from = "/antora/latest/*"
to = "/antora/1.1/:splat"
status = 302
