= Antora Documentation Site
// Settings:
:hide-uri-scheme:
ifdef::env-gitlab[:badges:]
// Project URIs:
:uri-project: https://antora.org
:uri-docs: https://docs.antora.org
:uri-install: {uri-docs}/antora/1.0/install/install-antora/
:uri-repo-core: https://gitlab.com/antora/antora
:uri-repo-ui: https://gitlab.com/antora/antora-ui-default
// External URIs:
:uri-letsencrypt: https://letsencrypt.org
:uri-netlify: https://www.netlify.com
:uri-netlify-deploys: https://app.netlify.com/sites/antora-docs/deploys
:uri-opendevise: https://opendevise.com

ifdef::badges[]
image:https://gitlab.com/antora/docs.antora.org/badges/master/pipeline.svg[CI status,116,20,link=https://gitlab.com/antora/docs.antora.org/pipelines]
image:https://www.netlify.com/img/global/badges/netlify-dark.svg[Deploy Status,45,20,link={uri-netlify-deploys}]
endif::[]

This repository contains the playbook project for the Antora documentation site published at {uri-docs}.

== Documentation Structure

The documentation components are pulled from the {uri-repo-core}[Antora Core components] and {uri-repo-ui}[Antora Default UI] repositories.
The site uses the Antora Default UI to generate its UI (i.e., the web pages).

== Quickstart

To generate the Antora Docs site, you first need to {uri-install}[install Antora].
Once Antora is installed, run the `antora` command using the playbook file hosted in this repository.

 $ antora site.yml

The site will be generated into [.path]_public/_.
Navigate to [.path]_public/index.html_ in your browser to view the site offline.

== Hosting

This site is hosted on {uri-netlify}[Netlify].
It is managed by the account info [at] this domain.

Deployment is triggered via a webhook on the master branch of the git repository (URL: https://api.netlify.com/hooks/gitlab, events: Push Events, Merge Requests Events).

The deploy job on Netlify is configured by the file [.path]_netlify.toml_.
This configuration files defines certain environment variables that control the behavior of Yarn and Antora.
When the job runs, it switches to the [.path]_netlify/_ directory, runs `yarn`, then invokes `antora`.

////
The site is built on GitLab CI then deployed to Netlify using the Netlify CLI (command: `netlify`).
The CI job that deploys the site to Netlify is configured by the file [.path]_.gitlab-ci.yml_.
The secret variables required for deploying to Netlify (NETLIFY_SITE_ID and NETLIFY_ACCESS_TOKEN) are maintained in the CI configuration of this repository.
////

The deploy logs for antora.org can be viewed at {uri-netlify-deploys}.

== Domain Name

The domain name for this site is configured using the following A record:

 docs 3600 IN A 104.198.14.52

The certificate for this site was generated by {uri-letsencrypt}[Let's Encrypt] and is shared with the certificate for antora.org.
See the https://gitlab.com/antora/antora.org/blob/master/README.adoc[antora.org README] for details about how it was generated and configured.

== TLS Certificate (https)

The TLS certificate for docs.antora.org was issued by {uri-netlify}[Netlify] using {uri-letsencrypt}[Let's Encrypt] and is automatically renewed.

Verify the certificate is valid using:

 $ curl -vI https://docs.antora.org

Look for `CN=docs.antora.org` under the "`Server certificate`" section.

Netlify redirects all traffic to HTTPS automatically (i.e., it forces HTTPS).

== Copyright and License

Copyright (C) 2017-2018 {uri-opendevise}[OpenDevise Inc.] and individual contributors to docs.antora.org.

Except where otherwise noted, docs.antora.org, Antora, and the Antora UI, are licensed under the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to view the full license text.
