= Antora Documentation Site
// Settings:
:hide-uri-scheme:
ifdef::env-gitlab[:badges:]
// Project URLs
:url-project: https://antora.org
:url-docs: https://docs.antora.org
:url-install: {url-docs}/antora/latest/install/install-antora/
:url-org: https://gitlab.com/antora
:url-repo-core: {url-org}/antora
:url-repo-ui: {url-org}/antora-ui-default
// External URLs
:url-letsencrypt: https://letsencrypt.org
:url-netlify: https://www.netlify.com
:url-netlify-deploys: https://app.netlify.com/sites/antora-docs/deploys
:url-opendevise: https://opendevise.com

ifdef::badges[]
image:https://gitlab.com/antora/docs.antora.org/badges/master/pipeline.svg[CI status,116,20,link=https://gitlab.com/antora/docs.antora.org/pipelines]
image:https://www.netlify.com/img/global/badges/netlify-dark.svg[Deploy Status,45,20,link={url-netlify-deploys}]
endif::[]

This repository contains the playbook project for the Antora documentation site published at {url-docs}.

== Documentation Structure

The documentation components are pulled from the {url-repo-core}[Antora] and {url-repo-ui}[Antora Default UI] repositories.
The site uses the Antora Default UI to generate its UI (i.e., the web pages).

== Quickstart

To generate the Antora Docs site, you first need to {url-install}[install Antora].
Once Antora is installed, run the `antora` command on the playbook file hosted in this repository.

 $ antora antora-playbook.yml

The site will be generated into [.path]_public/_.
Navigate to [.path]_public/index.html_ in your browser to view the site offline.

== Hosting

This site is hosted on {url-netlify}[Netlify].
It is managed by the account info [at] this domain.

Deployment is triggered via a webhook on the master branch of the git repository (URL: https://api.netlify.com/hooks/gitlab, events: Push Events, Merge Requests Events).

The deploy job on Netlify is configured by the file [.path]_netlify.toml_.
This configuration files defines certain environment variables that control the behavior of Yarn and Antora.
When the job runs, it switches to the [.path]_netlify/_ directory, runs `yarn`, then invokes `antora`.

The Netlify deploy logs for antora.org can be viewed at {url-netlify-deploys}.

The site is also built nightly on GitLab CI.
Not only does this allow the site to be updated on a schedule, it also allows us to test the Antora Docker image.
The nightly CI job, which is configured in the file [.path]_.gitlab-ci.yml_, generates the site using Antora then deploys it to Netlify using the Netlify CLI (command: `netlify`).
The secret variables required for deploying to Netlify (NETLIFY_SITE_ID and NETLIFY_ACCESS_TOKEN) are defined on the scheduled job configuration page.

== Domain Name

The domain name for this site is configured using the following A record:

 docs 3600 IN A 104.198.14.52

The certificate for this site was generated by {url-letsencrypt}[Let's Encrypt] and is shared with the certificate for antora.org.
See the https://gitlab.com/antora/antora.org/blob/master/README.adoc[antora.org README] for details about how it was generated and configured.

== TLS Certificate (https)

The TLS certificate for docs.antora.org was issued by {url-netlify}[Netlify] using {url-letsencrypt}[Let's Encrypt] and is automatically renewed.

Verify the certificate is valid using:

 $ curl -vI https://docs.antora.org

Look for `CN=docs.antora.org` under the "`Server certificate`" section.

Netlify redirects all traffic to HTTPS automatically (i.e., it forces HTTPS).

== Copyright and License

Copyright (C) 2017-2019 {url-opendevise}[OpenDevise Inc.] and individual contributors to docs.antora.org.

Except where otherwise noted, docs.antora.org, Antora, and the Antora UI, are licensed under the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to view the full license text.
