= Antora Documentation Site
// Settings:
:hide-uri-scheme:
// Project URIs:
:uri-project: https://antora.org
:uri-docs: https://docs.antora.org
:uri-repo-core: https://gitlab.com/antora/antora
:uri-repo-ui: https://gitlab.com/antora/antora-ui-default
// External URIs:
:uri-gitlab-pages: https://about.gitlab.com/features/pages/
:uri-letsencrypt: https://letsencrypt.org
:uri-opendevise: https://opendevise.com

This repository contains the playbook project for the Antora documentation site published at {uri-docs}.

== Documentation Structure

The documentation components are pulled from the {uri-repo-core}[Antora Core] and {uri-repo-ui}[Antora Default UI] repositories.
The site uses the Antora Default UI to generate its UI (i.e., the web pages).

== Quickstart

To generate the Antora Docs site, you first need to {uri-repo-core}/blob/master/README.adoc[install Antora].
Once Antora installed, run the `antora` command using the playbook file hosted in this repository.

 $ antora site.yml

The site will be generated into [.path]_public/_.
Navigate to the [.path]_public/index.html_ in your browser to view the site offline.

== Hosting

This site is hosted using {uri-gitlab-pages}[GitLab Pages].
The CI job that deploys the site is configured by the file [.path]_.gitlab-ci.yml_.

== Domain Name & TLS Certificate (https)

The domain name for this site is configured using the following A record:

 docs 3600 IN A 52.167.214.135

The certificate for this site was generated by {uri-letsencrypt}[Let's Encrypt] and is shared with the certificate for antora.org.
See the https://gitlab.com/antora/antora.org/blob/master/README.adoc[antora.org README] for details about how it was generated and configured.

== Copyright

Copyright (C) 2017-2018 {uri-opendevise}[OpenDevise Inc.] and the {uri-project}[Antora Project].
