site:
  title: Antora Docs
  url: https://docs.antora.org
  start_page: antora::index
content:
  sources:
  - url: https://gitlab.com/antora/antora
    branches: master
    start_path: docs
  - url: https://gitlab.com/antora/antora-ui-default
    branches: master
    start_path: docs
ui:
  bundle: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: supplemental-ui
output:
  dir: public
